# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_RESCTRL_RISCV_CBQRI_CACHE)      += cbqri_cache.o
obj-$(CONFIG_RESCTRL_RISCV_CBQRI_BANDWIDTH)  += cbqri_bandwidth.o
obj-$(CONFIG_RESCTRL_RISCV_CBQRI_XL300)      += xl300_cbqri.o
